apiVersion: v2
name: fitness-tracker
description: A Helm chart for Fitness Tracker application with PostgreSQL, Redis, and monitoring
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/your-org/fitness-tracker
sources:
- https://github.com/your-org/fitness-tracker
maintainers:
- name: DevOps Team
  email: devops@company.com
keywords:
- fitness
- health
- tracking
- react
- nodejs
- postgresql
- redis

dependencies:
- name: postgresql
  version: 12.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 17.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: prometheus
  version: 25.x.x
  repository: https://prometheus-community.github.io/helm-charts
  condition: monitoring.prometheus.enabled
- name: grafana
  version: 6.x.x
  repository: https://grafana.github.io/helm-charts
  condition: monitoring.grafana.enabled

annotations:
  category: Application