apiVersion: v1
kind: Secret
metadata:
  name: fitness-tracker-secrets
  namespace: fitness-tracker
  labels:
    app.kubernetes.io/name: fitness-tracker
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  # echo -n "your-password" | base64
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2tleSA=  # your_jwt_secret_key 
  SESSION_SECRET: eW91cl9zZXNzaW9uX3NlY3JldF9rZXk=  # your_session_secret_key

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: fitness-tracker
  labels:
    app.kubernetes.io/name: fitness-tracker
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # Replace with your actual TLS certificate and key (base64 encoded)
  tls.crt: LS0tLS1CRUdJTi... # Base64 encoded TLS certificate
  tls.key: LS0tLS1CRUdJTi... # Base64 encoded TLS private key